name: CI - Code Quality and StyleCop Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-latest

    env:
      WARN_AS_ERROR: ""

    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # Install necessary tools and add StyleCop to all projects
      - name: Install Tools
        run: |
          dotnet tool install -g dotnet-format
          dotnet add AppLidra.Client/AppLidra.Client.csproj package StyleCop.Analyzers
          dotnet add AppLidra.Server/AppLidra.Server.csproj package StyleCop.Analyzers
          dotnet add AppLidra.Shared/AppLidra.Shared.csproj package StyleCop.Analyzers

      # Build all projects with StyleCop enabled
      - name: Run StyleCop Analysis
        run: |
          dotnet build AppLidra.Client/AppLidra.Client.csproj --configuration Release --no-restore ${{ env.WARN_AS_ERROR }}
          dotnet build AppLidra.Server/AppLidra.Server.csproj --configuration Release --no-restore ${{ env.WARN_AS_ERROR }}
          dotnet build AppLidra.Shared/AppLidra.Shared.csproj --configuration Release --no-restore ${{ env.WARN_AS_ERROR }}

      # Run tests
      - name: Run Tests
        run: dotnet test AppLidra.sln --no-restore --verbosity normal

      # Check code format
      - name: Check C# Code Format
        run: dotnet format AppLidra.sln --check

      # Spell check comments
      - name: Check Comments for Spelling Errors
        run: |
          pip install codespell
          codespell --skip=".git,bin,obj,node_modules" --ignore-words-list="Http,Json"
